### ISSUE TITLE
Systemowe diagramy sekwencyjne

### ISSUE THREAD

**Issue by Zax37** [IrminaWalawska/IO4#26]
@Zax37 - Menadżer, Administrator
@JakubGorski - System analizy sprzedaży(/księgowy), Magazynier
@marcin-kur - Peryferia(czytnik kodów, terminal)

**Comment by Zax37** [comment]
![image](https://cloud.githubusercontent.com/assets/6232228/24927454/62975e96-1eff-11e7-9106-5efa65e13a62.png)
![image](https://cloud.githubusercontent.com/assets/6232228/24927467/6ed29a72-1eff-11e7-9888-15b38fccccec.png)

**Comment by Zax37** [comment]
@JakubGorski - czy oba Twoje diagramy są już zrobione?

**Comment by JakubGorski** [comment]
Tak, zamykam.
