### ISSUE TITLE
Przeniesienie ciągów tekstowych do pliku json

### ISSUE THREAD

**Issue by Zax37** [IrminaWalawska/IO4#46]
Wszystkie ciągi tekstowe z widoków(logowanie, nowa transakcja sprzedaży) należy przetłumaczyć i przenieść do pliku "/assets/lang/en.json". Opcjonalnie utworzyć drugi plik "pl.json" z polskimi odpowiednikami ciągów tekstowych.

Ciąg tekstowy pobieramy z pliku w następujący sposób: Model.getString("NAZWA_CIĄGU").

**Comment by Dyju711** [comment]
1p
