### ISSUE TITLE
Interfejs i wrapper dla magazynu

### ISSUE THREAD

**Issue by Zax37** [IrminaWalawska/IO4#50]
Analogicznie do systemów autentykacji i kalkulatora podatkowego zaprojektować wsparcie dla zewnętrznego systemu magazynowego, wystarczy jedna metoda np. receiveDelivery() zwracająca mapę <Product, int> z ilością dostarczonego produktu(może być zawsze 1 tego samego produktu).

1p

**Comment by jperek** [comment]
done in 2367ee453a3f347310484b75d2923ebaa13edd8c
